[package]
name = "crate-docs"
version = "0.1.0"
authors = ["Dustin Knopoff <dustinknopoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "*", features =["full"]}
shipyard = "*"
specs = "*"
chrono = "*"
sqlx = "*"
pest = "*"
walkdir = "*"
