name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: rsdocs-dashing installation
        run: cargo +stable install rsdocs-dashing
      - name: dashing installation
        run: go get -u github.com/technosophos/dashing
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Doc
        run: cargo doc
