name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: "1.*" # The Go version to download (if necessary) and use.
      - name: dashing installation
        run: mkdir dashing; GOPATH=`pwd`/dashing go get -u github.com/technosophos/dashing
      - name: rsdocs-dashing installation
        run: cargo +stable install rsdocs-dashing
      - name: Doc
        run: cargo doc
      - name: Build docsets
        run: bash build-docsets.sh
      - name: Check for docsets
        run: |
          mkdir docsets
          for i in *.docset; do 
          mv $i docsets/
          tar --exclude='.DS_Store' -cvzf ${i/.docset}.tgz $i
          done
          ls docsets
      - name: Create and Upload Release Asset
        id: upload-release-asset
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            docsets/*.tgz
            crates.txt
